source 'http://rubygems.org'

gem 'rails', '3.0.9'

gem 'dm-core', '~> 1.1.0'
gem 'dm-active_model', '~> 1.1.0'
gem 'dm-rails', '~> 1.1.0'
gem 'dm-redis-adapter', '~> 0.4.0'
gem 'dm-serializer', '~> 1.1.0'
gem 'dm-timestamps', '~> 1.1.0'
gem 'dm-validations', '~> 1.1.0'
gem 'dm-types', '~> 1.1.0'
# gem 'dm-aggregates', '~> 1.1.0'
# gem 'dm-accepts_nested_attributes', :git => 'git://github.com/danryan/dm-accepts_nested_attributes.git'
gem 'resque'
gem 'resque-scheduler', :require => 'resque/scheduler'
gem 'yajl-ruby', :require => 'yajl'
gem 'slim'
gem 'sass', '~> 3.1.3'
gem 'hashie'
gem 'rest-client'
gem 'simple_form'
gem 'show_for'
gem 'table_for'
gem 'interpolate'

group :development, :test do
  gem "flutie", "~> 1.1"  
  gem 'shoulda'
  gem 'jquery-rails'
  gem "slim-rails"
  gem 'rails3-generators'
  gem 'rspec-rails', '~> 2.6.0'
  gem 'spork', '~> 0.9.0.rc8'
  gem 'watchr', '~> 0.7'
  gem 'rack-test'
  gem 'ruby-debug-base19', '0.11.24'
  gem 'ruby-debug19', '0.11.6'
  gem 'factory_girl_rails'
end
